apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: 192.168.56.201, internalAddress: 192.168.56.201, user: root, password: "admin"}
  - {name: master2, address: 192.168.56.202, internalAddress: 192.168.56.202, user: root, password: "admin"}
  - {name: master3, address: 192.168.56.203, internalAddress: 192.168.56.203, user: root, password: "admin"}
  - {name: worker1, address: 192.168.56.251, internalAddress: 192.168.56.251, user: root, password: "admin"}
  - {name: worker2, address: 192.168.56.252, internalAddress: 192.168.56.252, user: root, password: "admin"}
  - {name: lb1, address: 192.168.56.101, internalAddress: 192.168.56.101, user: root, password: "admin"}
  - {name: lb2, address: 192.168.56.102, internalAddress: 192.168.56.102, user: root, password: "admin"}
  roleGroups:
    etcd:
    - master1
    - master2
    - master3
    control-plane: 
    - master1
    - master2
    - master3
    worker:
    - worker1
    - worker2
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers 
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: "192.168.56.100"
    port: 6443
  kubernetes:
    version: v1.22.12
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: docker
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []